# Generated by Django 4.1 on 2022-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_checkout_message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
